exclude:
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md
- dap.md
- uxtesting.md
- work
- ".sass-cache"

# Site metadata
title: "analytics.techoats.com | How many oats?"
description: "Testing and tinkering"

# site's own URL, and data root
url: https://analytics.techoats.com
data_url: https://analytics.techoats.com/data

# GitHub information
org_name: snowulf
repo_name: test

# twitter information
twitter: techoats
